// Interface strings (chrome only). Course content never lives here.
const strings = {
  en: {
    contents: 'Contents',
    chapter: 'Chapter',
    search: 'Search',
    searchPlaceholder: 'Search the reference…',
    searchHint: 'Type to search titles and text',
    noResults: 'No matches',
    close: 'Close',
    openMenu: 'Open navigation',
    closeMenu: 'Close navigation',
    switchLang: 'العربية',
    switchLangLabel: 'Switch to Arabic',
    theme: 'Toggle theme',
    light: 'Light',
    dark: 'Dark',
    previous: 'Previous',
    next: 'Next',
    printAll: 'Print the whole reference',
    printView: 'Print view',
    printViewNote: 'Every chapter, in order. Use your browser’s Print command to save a PDF.',
    backToReference: 'Back to the reference',
    placeholder: 'Image placeholder',
    expectedFile: 'Expected file',
    tip: 'Tip',
    warning: 'Warning',
    quote: 'Quote',
    note: 'Added for this course',
    linkToSection: 'Link to this section',
    onThisPage: 'On this page',
    keyboardHint: 'Navigate',
    keyboardSelect: 'Open',
    keyboardClose: 'Close',
    inChapter: 'in',
    addNote: 'Note',
    noteDialog: 'Add a note to the selected text',
    notePlaceholder: 'Write a note…',
    saveNote: 'Save',
    noteSaved: 'Note saved',
    cancel: 'Cancel',
  },
  ar: {
    contents: 'المحتويات',
    chapter: 'فصل',
    search: 'بحث',
    searchPlaceholder: 'ابحث في المرجع…',
    searchHint: 'اكتب للبحث في العناوين والنصوص',
    noResults: 'لا توجد نتائج',
    close: 'إغلاق',
    openMenu: 'فتح القائمة',
    closeMenu: 'إغلاق القائمة',
    switchLang: 'English',
    switchLangLabel: 'التبديل إلى الإنجليزية',
    theme: 'تبديل السمة',
    light: 'فاتح',
    dark: 'داكن',
    previous: 'السابق',
    next: 'التالي',
    printAll: 'طباعة المرجع كاملًا',
    printView: 'نسخة الطباعة',
    printViewNote: 'كل الفصول بالترتيب. استخدم أمر الطباعة في المتصفح لحفظ ملف PDF.',
    backToReference: 'العودة إلى المرجع',
    placeholder: 'صورة مؤقتة',
    expectedFile: 'الملف المتوقع',
    tip: 'نصيحة',
    warning: 'تنبيه',
    quote: 'اقتباس',
    note: 'إضافة خاصة بالكورس',
    linkToSection: 'رابط هذا القسم',
    onThisPage: 'في هذه الصفحة',
    keyboardHint: 'تنقّل',
    keyboardSelect: 'فتح',
    keyboardClose: 'إغلاق',
    inChapter: 'في',
    addNote: 'ملاحظة',
    noteDialog: 'أضف ملاحظة على النص المحدد',
    notePlaceholder: 'اكتب ملاحظة…',
    saveNote: 'حفظ',
    noteSaved: 'تم حفظ الملاحظة',
    cancel: 'إلغاء',
  },
}

export function t(lang, key) {
  return strings[lang]?.[key] ?? strings.en[key] ?? key
}
